//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.28 at 11:00:11 PM CET 
//


package com.udemyspringbootsoapproject.courses;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="courseDetails">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="courseId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="courseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="courseDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "courseDetails"
})
@XmlRootElement(name = "GetCourseDetailsReponse")
public class GetCourseDetailsReponse {

    @XmlElement(required = true)
    protected GetCourseDetailsReponse.CourseDetails courseDetails;

    /**
     * Gets the value of the courseDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GetCourseDetailsReponse.CourseDetails }
     *     
     */
    public GetCourseDetailsReponse.CourseDetails getCourseDetails() {
        return courseDetails;
    }

    /**
     * Sets the value of the courseDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GetCourseDetailsReponse.CourseDetails }
     *     
     */
    public void setCourseDetails(GetCourseDetailsReponse.CourseDetails value) {
        this.courseDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="courseId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="courseName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="courseDescription" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "courseId",
        "courseName",
        "courseDescription"
    })
    public static class CourseDetails {

        protected int courseId;
        @XmlElement(required = true)
        protected String courseName;
        @XmlElement(required = true)
        protected String courseDescription;

        /**
         * Gets the value of the courseId property.
         * 
         */
        public int getCourseId() {
            return courseId;
        }

        /**
         * Sets the value of the courseId property.
         * 
         */
        public void setCourseId(int value) {
            this.courseId = value;
        }

        /**
         * Gets the value of the courseName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCourseName() {
            return courseName;
        }

        /**
         * Sets the value of the courseName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCourseName(String value) {
            this.courseName = value;
        }

        /**
         * Gets the value of the courseDescription property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCourseDescription() {
            return courseDescription;
        }

        /**
         * Sets the value of the courseDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCourseDescription(String value) {
            this.courseDescription = value;
        }

    }

}
