
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (1, 'Gabriela Mistral', 'Chile', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (2, 'Miguel Ángel Asturias', 'Guatemala', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (3, 'Pablo Neruda', 'Chile', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (4, 'Octavio Paz', 'México', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (5, 'Mario Vargas Llosa', 'Peru', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (6, 'José Luís Peixoto', 'Portugal', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (7, 'António Lobo Antunes', 'Portugal', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (8, 'Leopoldo Marechal', 'Argentina', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (9, 'José Lezama', 'Cuba', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (10, 'Luis Rafael Sánchez', 'Porto Rico', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (11, 'Gabriel García Márquez', 'Colombia', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (12, 'Isabel Allende', 'Chile', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (13, 'Juan Carlos Onetti', 'Uruguay', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (14, 'Eduardo Galeano', 'Uruguay', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (15, 'Roberto Arlt', 'Argentina', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (16, 'José Martí', 'Cuba', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (17, 'Jorge Luís Borges', 'Argentina', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (18, 'Julio Cortázar', 'Argentina', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (19, 'Jorge Amado', 'Brasil', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (20, 'Carlos Fuentes', 'México', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (21, 'Roberto Bolaño', 'Chile', sysdate());
insert into Author (author_id, author_name, author_nationality, author_birthdate) values (22, 'Mario Benedetti', 'Uruguay', sysdate());

insert into Book (book_id, book_name, author_id) values (1, 'Desolación', 1);
insert into Book (book_id, book_name, author_id) values (2, 'Cien años de Soledad', 11);
insert into Book (book_id, book_name, author_id) values (3, 'El amor en el tiempo del cólera', 11);
insert into Book (book_id, book_name, author_id) values (4, 'El coronel no tiene quien le escriba', 11);
insert into Book (book_id, book_name, author_id) values (5, 'Memorias de mis putas tristes', 11);
insert into Book (book_id, book_name, author_id) values (6, 'Veinte poemas de amor y una canción desesperada', 3);
insert into Book (book_id, book_name, author_id) values (7, 'Canto General', 3);
insert into Book (book_id, book_name, author_id) values (8, 'Cien sonetos de amor', 3);
insert into Book (book_id, book_name, author_id) values (9, 'La ciudad y los perros', 5);
insert into Book (book_id, book_name, author_id) values (10, 'La tía Julia y el escribidor', 5);
insert into Book (book_id, book_name, author_id) values (11, 'La fiesta del Chivo', 5);
insert into Book (book_id, book_name, author_id) values (12, 'Travesuras de la niña mala', 5);
insert into Book (book_id, book_name, author_id) values (13, 'El pozo', 13);
insert into Book (book_id, book_name, author_id) values (14, 'Tierra de nadie', 13);
insert into Book (book_id, book_name, author_id) values (15, 'Para esta noche', 13);
insert into Book (book_id, book_name, author_id) values (16, 'La vida breve', 13);
insert into Book (book_id, book_name, author_id) values (17, 'Ismaelillo', 16);
insert into Book (book_id, book_name, author_id) values (18, 'Versos sencillos', 16);
insert into Book (book_id, book_name, author_id) values (19, 'Inquisiciones', 17);
insert into Book (book_id, book_name, author_id) values (20, 'El tamaño de mi esperanza', 17);
insert into Book (book_id, book_name, author_id) values (21, 'Historia de la eternidad', 17);
insert into Book (book_id, book_name, author_id) values (22, 'Antología personal', 17);
insert into Book (book_id, book_name, author_id) values (23, 'Rayuela', 18);
insert into Book (book_id, book_name, author_id) values (24, 'Antología', 18);
insert into Book (book_id, book_name, author_id) values (25, 'Argentina, años de alambradas culturales', 18);
insert into Book (book_id, book_name, author_id) values (26, 'Salvo el crepúsculo', 18);
insert into Book (book_id, book_name, author_id) values (27, 'La casa de los espíritus', 12);
insert into Book (book_id, book_name, author_id) values (28, 'De amor y de sombra', 12);
insert into Book (book_id, book_name, author_id) values (29, 'El bosque de los pigmeos', 12);
insert into Book (book_id, book_name, author_id) values (30, 'El cuaderno de Maya', 12);
insert into Book (book_id, book_name, author_id) values (31, 'Mar Muerto', 19);
insert into Book (book_id, book_name, author_id) values (32, 'Capitanes de la arena', 19);
insert into Book (book_id, book_name, author_id) values (33, 'Gabriela, clavo y canela', 19);
insert into Book (book_id, book_name, author_id) values (34, 'Los pastores de la noche', 19);
insert into Book (book_id, book_name, author_id) values (35, 'El señor presidente', 2);
insert into Book (book_id, book_name, author_id) values (36, 'Hombres de maíz', 2);
insert into Book (book_id, book_name, author_id) values (37, 'La región más transparente', 20);
insert into Book (book_id, book_name, author_id) values (38, 'La muerte de Artemio Cruz', 20);
insert into Book (book_id, book_name, author_id) values (39, 'Aura', 20);
insert into Book (book_id, book_name, author_id) values (40, 'Ternura', 1);
insert into Book (book_id, book_name, author_id) values (41, 'Nubes blancas y breve descripción de Chile', 1);
insert into Book (book_id, book_name, author_id) values (42, 'Lagar', 1);
insert into Book (book_id, book_name, author_id) values (43, 'El laberinto de la Soledad', 4);
insert into Book (book_id, book_name, author_id) values (44, 'El arco y la lira', 4);
insert into Book (book_id, book_name, author_id) values (45, 'Sor Juana Inés de la Cruz o las trampas de la fe', 4);
insert into Book (book_id, book_name, author_id) values (46, '2666', 21);
insert into Book (book_id, book_name, author_id) values (47, 'Los detectives salvajes', 21);
insert into Book (book_id, book_name, author_id) values (48, 'El juguete rabioso', 15);
insert into Book (book_id, book_name, author_id) values (49, 'Los siete locos', 15);
insert into Book (book_id, book_name, author_id) values (50, 'El jorobadito', 15);
insert into Book (book_id, book_name, author_id) values (51, 'El criador de gorilas', 15);
insert into Book (book_id, book_name, author_id) values (52, 'Las venas abiertas de América Latina', 14);
insert into Book (book_id, book_name, author_id) values (53, 'Días y noches de amor y guerra', 14);
insert into Book (book_id, book_name, author_id) values (54, 'El libro de los abrazos', 14);
insert into Book (book_id, book_name, author_id) values (55, 'Las palabras andantes', 14);
insert into Book (book_id, book_name, author_id) values (56, 'La Guaracha del Macho Camacho', 10);
insert into Book (book_id, book_name, author_id) values (57, 'La guagua aérea', 10);
insert into Book (book_id, book_name, author_id) values (58, 'Tiempo negado', 9);
insert into Book (book_id, book_name, author_id) values (59, 'Paradiso', 9);
insert into Book (book_id, book_name, author_id) values (60, 'Muerte de Narciso', 9);
insert into Book (book_id, book_name, author_id) values (61, 'Aventuras sigilosas', 9);
insert into Book (book_id, book_name, author_id) values (62, 'Odas para el hombre y la mujer', 8);
insert into Book (book_id, book_name, author_id) values (63, 'Laberinto de amor', 8);
insert into Book (book_id, book_name, author_id) values (64, 'El centauro', 8);
insert into Book (book_id, book_name, author_id) values (65, 'Sonetos a Sophia', 8);
insert into Book (book_id, book_name, author_id) values (66, 'Cartas de la guerra', 7);
insert into Book (book_id, book_name, author_id) values (67, 'Memória de Elefante', 7);
insert into Book (book_id, book_name, author_id) values (68, 'No es medianoche quien quiere', 7);
insert into Book (book_id, book_name, author_id) values (69, 'Hasta que las piedras se vuelvan más leves que el agua', 7);
insert into Book (book_id, book_name, author_id) values (70, 'En tu vientre', 6);
insert into Book (book_id, book_name, author_id) values (71, 'Te me moriste', 6);
insert into Book (book_id, book_name, author_id) values (72, 'Nadie nos mira', 6);