insert into Author(id,first_name,last_name,email) values (1,'Nelson','Dias','nelson@nelsondias.net');
insert into Author(id,first_name,last_name,email) values (2,'Andre','Dias','nelson@nelsondias.net');

insert into Post(id,title,slug,teaser,body,author_id,posted_on) values (1,'Spring Boot Rocks!','spring-boot-rocks','Leonardo da Vinci by Walter Isaacson','His lack of reverence for authority and his willingness to challenge received wisdom would lead him to craft an empirical approach for understanding nature that foreshadowed the scientific method developed more than a century later by Bacon and Galileo. His method was rooted in experiment, curiosity, and the ability to marvel at phenomena that the rest of us rarely pause to ponder after we’ve outgrown our wonder years.',1,CURRENT_TIMESTAMP());
insert into Post(id,title,slug,teaser,body,author_id,posted_on) values (2,'Spring Data Rocks!','spring-data-rocks','Leonardo da Vinci by Walter Isaacson','His lack of reverence for authority and his willingness to challenge received wisdom would lead him to craft an empirical approach for understanding nature that foreshadowed the scientific method developed more than a century later by Bacon and Galileo. His method was rooted in experiment, curiosity, and the ability to marvel at phenomena that the rest of us rarely pause to ponder after we’ve outgrown our wonder years.',1,CURRENT_TIMESTAMP());
insert into Post(id,title,slug,teaser,body,author_id,posted_on) values (3,'Blog Post 1','nelson-blog-post-1','Leonardo da Vinci by Walter Isaacson','His lack of reverence for authority and his willingness to challenge received wisdom would lead him to craft an empirical approach for understanding nature that foreshadowed the scientific method developed more than a century later by Bacon and Galileo. His method was rooted in experiment, curiosity, and the ability to marvel at phenomena that the rest of us rarely pause to ponder after we’ve outgrown our wonder years.',2,CURRENT_TIMESTAMP());
insert into Post(id,title,slug,teaser,body,author_id,posted_on) values (4,'Blog Post 2','nelson-blog-post-2','Leonardo da Vinci by Walter Isaacson','His lack of reverence for authority and his willingness to challenge received wisdom would lead him to craft an empirical approach for understanding nature that foreshadowed the scientific method developed more than a century later by Bacon and Galileo. His method was rooted in experiment, curiosity, and the ability to marvel at phenomena that the rest of us rarely pause to ponder after we’ve outgrown our wonder years.',2,CURRENT_TIMESTAMP());
insert into Post(id,title,slug,teaser,body,author_id,posted_on) values (5,'Blog Post 3','nelson-blog-post-3','Leonardo da Vinci by Walter Isaacson','His lack of reverence for authority and his willingness to challenge received wisdom would lead him to craft an empirical approach for understanding nature that foreshadowed the scientific method developed more than a century later by Bacon and Galileo. His method was rooted in experiment, curiosity, and the ability to marvel at phenomena that the rest of us rarely pause to ponder after we’ve outgrown our wonder years.',2,CURRENT_TIMESTAMP());
insert into Post(id,title,slug,teaser,body,author_id,posted_on) values (6,'Refactoring our Spring Data Project','refactoring-spring-data-project','Leonardo da Vinci by Walter Isaacson','His lack of reverence for authority and his willingness to challenge received wisdom would lead him to craft an empirical approach for understanding nature that foreshadowed the scientific method developed more than a century later by Bacon and Galileo. His method was rooted in experiment, curiosity, and the ability to marvel at phenomena that the rest of us rarely pause to ponder after we’ve outgrown our wonder years.',1,CURRENT_TIMESTAMP());
