//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.02 at 08:29:51 PM CET 
//


package com.java.springbootsoapbasics.xmlJavaObjects;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.java.springbootsoapbasics.xmlJavaObjects package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.java.springbootsoapbasics.xmlJavaObjects
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllAuthorBooksRequest }
     * 
     */
    public GetAllAuthorBooksRequest createGetAllAuthorBooksRequest() {
        return new GetAllAuthorBooksRequest();
    }

    /**
     * Create an instance of {@link GetAllAuthorBooksResponse }
     * 
     */
    public GetAllAuthorBooksResponse createGetAllAuthorBooksResponse() {
        return new GetAllAuthorBooksResponse();
    }

    /**
     * Create an instance of {@link AuthorBooks }
     * 
     */
    public AuthorBooks createAuthorBooks() {
        return new AuthorBooks();
    }

    /**
     * Create an instance of {@link DeleteAuthorBooksResponse }
     * 
     */
    public DeleteAuthorBooksResponse createDeleteAuthorBooksResponse() {
        return new DeleteAuthorBooksResponse();
    }

    /**
     * Create an instance of {@link DeleteAuthorBooksRequest }
     * 
     */
    public DeleteAuthorBooksRequest createDeleteAuthorBooksRequest() {
        return new DeleteAuthorBooksRequest();
    }

    /**
     * Create an instance of {@link GetAuthorBooksResponse }
     * 
     */
    public GetAuthorBooksResponse createGetAuthorBooksResponse() {
        return new GetAuthorBooksResponse();
    }

    /**
     * Create an instance of {@link GetAuthorBooksRequest }
     * 
     */
    public GetAuthorBooksRequest createGetAuthorBooksRequest() {
        return new GetAuthorBooksRequest();
    }

}
